LambAndLentil.UI/Controllers/PlansController.cs
using System;
using LambAndLentil.Domain.Abstract;
using LambAndLentil.Domain.Entities;

namespace LambAndLentil.UI.Controllers
{
    public class PlansController : BaseAttachDetachController<Plan>
    {
        public PlansController(IRepository<Plan> repository) : base(repository) => Repo = repository; 
    } 
}

LambAndLentil.UI/Views/Plans/Details.cshtml
@model LambAndLentil.UI.Models.Plan
@using LambAndLentil.Domain.Entities
@{ 
    string requestActionMethod = Request.AppRelativeCurrentExecutionFilePath.Split('/').Last();
    string actionMethod = ViewBag.ActionMethod == null ? requestActionMethod : ViewBag.ActionMethod.ToString();
    ViewBag.Title = actionMethod + " Plan";
    string colon = " : ";
    if (actionMethod == UIViewType.Edit.ToString())
    {
        actionMethod = UIViewType.PostEdit.ToString();
    }
    if (actionMethod == UIViewType.Create.ToString())
    {
        actionMethod = UIViewType.PostEdit.ToString();
    }
}


@if (actionMethod == UIViewType.Delete.ToString())
{
    <h2>@actionMethod Plan  &nbsp;:&nbsp; @Model.Name   ?</h2>
}
else if (actionMethod == UIViewType.Details.ToString())
{
    <h2>Plan Details for @Model.Name</h2>
}
else if (actionMethod == UIViewType.PostEdit.ToString())
{
    if (Model.ID ==0)
    {
        <h2> Create New Plan</h2>
    }
    else
    {
        <h2>Edit Details for @Model.Name Plan</h2>
    }
}
else
{
    string modelLabel = Model.Name == null ? " " : Model.Name == "Newly Created" ? " " : Model.Name;   
    <h2>@actionMethod Plan  &nbsp;:&nbsp;@modelLabel </h2>
}

<hr />
@using (Html.BeginForm(actionMethod, UIControllerType.Plans.ToString(), FormMethod.Post, new { id = Model.ID, planVM = Model }))
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)
    <div class="item">
        <div class="row">
            <div class="col-md-6">
                <ul>
                    <li>@Html.EditorFor(model => model.Name, new { valueM = Model.Name })</li>
                    <li>@Html.EditorFor(model => model.Description, new { valueM = Model.Description })</li> 
                </ul>
            </div>
             
            <div class="col-md-6">
                <ul> 
                    <li>@Html.EditorFor(model => model.AddedByUser, new { valueM = Model.AddedByUser, readOnly = true }) </li>
                    <li>@Html.EditorFor(model => model.CreationDate, new { valueM = Model.CreationDate, readOnly = true }) @Html.HiddenFor(model => model.CreationDate)</li>
                    <li>@Html.EditorFor(model => model.ModifiedByUser, new { valueM = Model.ModifiedByUser, readOnly = true }) </li>
                    <li>@Html.EditorFor(model => model.ModifiedDate, new { valueM = Model.ModifiedDate, readOnly = true }) @Html.HiddenFor(model => model.ModifiedDate)</li> 
                </ul>
            </div> 
        </div>
    </div>
   

    if (actionMethod == UIViewType.PostEdit.ToString() || actionMethod == UIViewType.Create.ToString())
    {
        <div class="form-group">
            <div>
                <input type="submit" value="Save Changes" class="btn btn-default col-md-offset-2 col-md-10" />
            </div>
        </div>


    }

}

@if (actionMethod == UIViewType.Create.ToString())
{
    <div>
        @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(Plan), @class = "btn btn-default" })
    </div>

}

@if (actionMethod == UIViewType.PostEdit.ToString())
{
    <div>
        @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(Plan), @class = "btn btn-default" })
        @if(Model.ID!=0)
        { 
        @Html.ActionLink("Delete", UIViewType.Delete.ToString(), null, new { id = Model.ID }, new { @class = "btn btn-default" })
        }
    </div>

}


@if (actionMethod == UIViewType.Delete.ToString())
{
    <h3>Are you sure you want to delete this plan: (@Model.Name) ?</h3>

    @Html.ActionLink("No - Back to List", UIViewType.Index.ToString(), null, new { @class = "btn btn-default" })
    using (Html.BeginForm(UIViewType.DeleteConfirmed.ToString(), UIControllerType.Plans.ToString(), new { id = Model.ID }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div>
                <input type="submit" value="Yes - Delete" class="btn btn-default" />
            </div>
        </div>
    }
}
@if (actionMethod == UIViewType.Details.ToString())
{
    <div>
        @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(Plan), @class = "btn btn-default" })
        @Html.ActionLink("Edit", UIViewType.Edit.ToString(), null, new { id = Model.ID, actionMethod = UIViewType.Edit.ToString() }, new { @class = "btn btn-default" }) 
        @Html.ActionLink("Delete", UIViewType.Delete.ToString(), null, new { id = Model.ID }, new { @class = "btn btn-default" })

    </div>

}

LambAndLentil.UI/Views/Plans/Index.cshtml
 @model LambAndLentil.UI.Models.ListVM
@{
    ViewBag.Title = "Plan Index";
    string sourceActionMethod = "PlansIndex";
}

<h2>Plans</h2>

<p>
    @Html.ActionLink("Add Plan", LambAndLentil.UI.UIViewType.Create.ToString(), UIControllerType.Plans.ToString(), new { actionMethod = UIViewType.Create.ToString() }, null)

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Plans.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plans.First().Description)
        </th> 
        <th></th>
    </tr>

@foreach (var item in Model.Plans) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>  
        <td>
            @Html.ActionLink(" ", UIViewType.Edit.ToString(), "Plans", new { id = item.ID, sourceActionMethod, actionMethod = UIViewType.Edit }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-edit", @title = "Edit" })
        </td>
        <td>
            @Html.ActionLink(" ", UIViewType.Details.ToString(), new { id = item.ID }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-list", @title = "Details" })
        </td>
        <td>
            @Html.ActionLink(" ", UIViewType.Details.ToString(), new
       {
           id = item.ID,
           actionMethod = UIViewType.Delete
       }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-trash", @title = "Delete" })
        </td>
    </tr>
}

</table>

<div class="pager">
    <h4>Lamb & Lentil</h4>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action(UIViewType.Index.ToString(), new { page = x }))
</div>