LambAndLentil.UI/Controllers/ShoppingListsController.cs
using LambAndLentil.Domain.Abstract;
using LambAndLentil.Domain.Entities;

namespace LambAndLentil.UI.Controllers
{
    public class ShoppingListsController : BaseAttachDetachController<ShoppingList>
    {
        public ShoppingListsController(IRepository<ShoppingList> repository) : base(repository) =>
                     Repo = repository;
    }
}

LambAndLentil.UI/Views/ShoppingLists/Details.cshtml
@model LambAndLentil.UI.Models.ShoppingList
@using LambAndLentil.Domain.Entities
@{
    //  string requestActionMethod = Request.AppRelativeCurrentExecutionFilePath.Split('/').Reverse().Skip(1).Take(1).FirstOrDefault();
    string requestActionMethod = Request.AppRelativeCurrentExecutionFilePath.Split('/').Last();
    string actionMethod = ViewBag.ActionMethod == null ? requestActionMethod : ViewBag.ActionMethod.ToString();
    ViewBag.Title = actionMethod + " ShoppingList";
    string colon = " : ";
    if (actionMethod == UIViewType.Edit.ToString())
    {
        actionMethod = UIViewType.PostEdit.ToString();
    }
    if (actionMethod == UIViewType.Create.ToString())
    {
        actionMethod = UIViewType.PostEdit.ToString();
    }
}


@if (actionMethod == UIViewType.Delete.ToString())
{
    <h2>@actionMethod ShoppingList  &nbsp;:&nbsp; @Model.Name   ?</h2>
}
else if (actionMethod == UIViewType.Details.ToString())
{
    <h2>ShoppingList Details for @Model.Name</h2>
}
else if (actionMethod == UIViewType.PostEdit.ToString())
{
    if (Model.ID ==0)
    {
        <h2> Create New ShoppingList</h2>
    }
    else
    {
        <h2>Edit Details for @Model.Name ShoppingList</h2>
    }
}
else
{
    string modelLabel = Model.Name == null ? " " : Model.Name == "Newly Created" ? " " : Model.Name;   
    <h2>@actionMethod ShoppingList  &nbsp;:&nbsp;@modelLabel </h2>
}

<hr />
@using (Html.BeginForm(actionMethod, UIControllerType.ShoppingLists.ToString(), FormMethod.Post, new { id = Model.ID, ingredient = Model }))
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)
    <div class="item">
        <div class="row">
            <div class="col-md-6">
                <ul>
                    <li>@Html.EditorFor(model => model.Name, new { valueM = Model.Name })</li>
                    <li>@Html.EditorFor(model => model.Description, new { valueM = Model.Description })</li>
                    <li>@Html.EditorFor(model=>model.Date, new {valueM=Model.Date})</li>
                    <li>@Html.EditorFor(model => model.Author, new { valueM = Model.Author })  </li> 
                </ul>
            </div>
             
            <div class="col-md-6">
                <ul> 
                    <li>@Html.EditorFor(model => model.AddedByUser, new { valueM = Model.AddedByUser, readOnly = true }) </li>
                    <li>@Html.EditorFor(model => model.CreationDate, new { valueM = Model.CreationDate, readOnly = true }) @Html.HiddenFor(model => model.CreationDate)</li>
                    <li>@Html.EditorFor(model => model.ModifiedByUser, new { valueM = Model.ModifiedByUser, readOnly = true }) </li>
                    <li>@Html.EditorFor(model => model.ModifiedDate, new { valueM = Model.ModifiedDate, readOnly = true }) @Html.HiddenFor(model => model.ModifiedDate)</li> 
                </ul>
            </div> 
        </div>
    </div>
   

    if (actionMethod == UIViewType.PostEdit.ToString() || actionMethod == UIViewType.Create.ToString())
    {
        <div class="form-group">
            <div>
                <input type="submit" value="Save Changes" class="btn btn-default col-md-offset-2 col-md-10" />
            </div>
        </div>


    }

}

@if (actionMethod == UIViewType.Create.ToString())
{
    <div>
        @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(ShoppingList), @class = "btn btn-default" })
    </div>

}

@if (actionMethod == UIViewType.PostEdit.ToString())
{
    <div>
        @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(ShoppingList), @class = "btn btn-default" })
        @if(Model.ID!=0)
        { 
        @Html.ActionLink("Delete", UIViewType.Delete.ToString(), null, new { id = Model.ID }, new { @class = "btn btn-default" })
        }
    </div>

}


@if (actionMethod == UIViewType.Delete.ToString())
{
    <h3>Are you sure you want to delete this shopping list: (@Model.Name) ?</h3>

    @Html.ActionLink("No - Back to List", UIViewType.Index.ToString(), null, new { @class = "btn btn-default" })
    using (Html.BeginForm(UIViewType.DeleteConfirmed.ToString(), UIControllerType.ShoppingLists.ToString(), new { id = Model.ID }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div>
                <input type="submit" value="Yes - Delete" class="btn btn-default" />
            </div>
        </div>
    }
}
@if (actionMethod == UIViewType.Details.ToString())
{
    <div>
        @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(ShoppingList), @class = "btn btn-default" })
        @Html.ActionLink("Edit", UIViewType.Edit.ToString(), null, new { id = Model.ID, actionMethod = UIViewType.Edit.ToString() }, new { @class = "btn btn-default" }) 
        @Html.ActionLink("Delete", UIViewType.Delete.ToString(), null, new { id = Model.ID }, new { @class = "btn btn-default" })

    </div>

}

LambAndLentil.UI/Views/ShoppingLists/Index.cshtml
 @model LambAndLentil.UI.Models.ListVM
@{
    ViewBag.Title = "ShoppingList Index";
    string sourceActionMethod = "ShoppingListsIndex";
}

<h2>ShoppingLists</h2>

<p>
    @Html.ActionLink("Add ShoppingList", LambAndLentil.UI.UIViewType.Create.ToString(), UIControllerType.ShoppingLists.ToString(), new { actionMethod = UIViewType.Create.ToString() }, null)

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ShoppingLists.First().Name)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.ShoppingLists.First().Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShoppingLists.First().Author)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.ShoppingLists) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td> 
        <td>
            @Html.ActionLink(" ", UIViewType.Edit.ToString(), "ShoppingLists", new { id = item.ID, sourceActionMethod, actionMethod = UIViewType.Edit }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-edit", @title = "Edit" })
        </td>
        <td>
            @Html.ActionLink(" ", UIViewType.Details.ToString(), new { id = item.ID }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-list", @title = "Details" })
        </td>
        <td>
            @Html.ActionLink(" ", UIViewType.Details.ToString(), new
       {
           id = item.ID,
           actionMethod = UIViewType.Delete
       }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-trash", @title = "Delete" })
        </td>
    </tr>
}

</table> 
<div class="pager">
    <h4>Lamb & Lentil</h4>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action(UIViewType.Index.ToString(), new { page = x }))
</div>

LambAndLentil.UI/Views/ShoppingLists/xxxEdit.cshtml
@model LambAndLentil.UI.Models.ShoppingList

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ShoppingList</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.BootstrapLabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.BootstrapLabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>