LambAndLentil.UI/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using LambAndLentil.Domain.Abstract;
using LambAndLentil.Domain.Entities;
using LambAndLentil.UI.Models;

namespace LambAndLentil.UI.Controllers
{ 
    public class MenusController :  BaseAttachDetachController<Menu> 
    {
        public MenusController(IRepository<Menu> repository) : base(repository) => Repo = repository;
    } 
} 

LambAndLentil.UI/Views/Menus/Details.cshtml
@model LambAndLentil.UI.Models.Menu
@using LambAndLentil.Domain.Entities
@{
    //  string requestActionMethod = Request.AppRelativeCurrentExecutionFilePath.Split('/').Reverse().Skip(1).Take(1).FirstOrDefault();
    string requestActionMethod = Request.AppRelativeCurrentExecutionFilePath.Split('/').Last();
    string actionMethod = ViewBag.ActionMethod == null ? requestActionMethod : ViewBag.ActionMethod.ToString();
    ViewBag.Title = actionMethod + " Menu";
    string colon = " : ";
    if (actionMethod == UIViewType.Edit.ToString())
    {
        actionMethod = UIViewType.PostEdit.ToString();
    }
    if (actionMethod == UIViewType.Create.ToString())
    {
        actionMethod = UIViewType.PostEdit.ToString();
    }

    string ingredientsValue = "empty";
    SelectList IngredientsList = ViewBag.listOfIngredients;
    if (IngredientsList == null)
    {
        IngredientsList = new SelectList(new List<string>());
    }
    else
    {
        ingredientsValue = IngredientsList.First().Value;
    }

    string value = "empty";
    SelectList RecipesList = ViewBag.listOfRecipes;
    if (RecipesList == null)
    {
        RecipesList = new SelectList(new List<string>());
    }
    else
    {
        value = RecipesList.First().Value;
    }
}


@if (actionMethod == UIViewType.Delete.ToString())
{
    <h2>@actionMethod Menu @colon @Model.Name   ?</h2>
}
else if (actionMethod == UIViewType.Details.ToString())
{
    <h2>Menu Details for @Model.Name</h2>
}
else if (actionMethod == UIViewType.PostEdit.ToString())
{
    if (Model.ID == 0)
    {
        <h2> Create New Menu</h2>
    }
    else
    {
        <h2>Edit Details for @Model.Name Menu</h2>
    }
}
else
{
    string modelLabel = Model.Name == null ? " " : Model.Name == "Newly Created" ? " " : Model.Name;
    <h2>@actionMethod Menu  @colon @modelLabel </h2>
}

<hr />
@using (Html.BeginForm(actionMethod, UIControllerType.Menus.ToString(), FormMethod.Post, new { id = Model.ID, menuVM = Model }))
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)
    <div class="item">
        <div class="row">
            <div class="col-md-6">
                <ul>
                    <li>@Html.EditorFor(model => model.Name, new { valueM = Model.Name })</li>
                    <li>@Html.EditorFor(model => model.Description, new { valueM = Model.Description })</li>
                    <li>@Html.EditorFor(model => model.MealType, new { valueM = Model.MealType })</li>
                    <li>@Html.EditorFor(model => model.DayOfWeek, new { valueM = Model.DayOfWeek })  </li>
                    <li>@Html.EditorFor(model => model.Diners, new { valueM = Model.Diners })</li>
                </ul>
            </div>

            <div class="col-md-6">
                <ul>
                    <li>@Html.EditorFor(model => model.AddedByUser, new { valueM = Model.AddedByUser, readOnly = true }) </li>
                    <li>@Html.EditorFor(model => model.CreationDate, new { valueM = Model.CreationDate, readOnly = true }) @Html.HiddenFor(model => model.CreationDate)</li>
                    <li>@Html.EditorFor(model => model.ModifiedByUser, new { valueM = Model.ModifiedByUser, readOnly = true }) </li>
                    <li>@Html.EditorFor(model => model.ModifiedDate, new { valueM = Model.ModifiedDate, readOnly = true })   @Html.HiddenFor(model => model.ModifiedDate)</li>
                </ul>
            </div>
        </div>
    </div>


    if (actionMethod == UIViewType.PostEdit.ToString() || actionMethod == UIViewType.Create.ToString())
    {
        <div class="form-group">
            <div>
                <input type="submit" value="Save Changes" class="btn btn-default col-md-offset-2 col-md-10" />
            </div>
        </div>


    }

}

@if (actionMethod == UIViewType.Create.ToString())
{
    <div>
        @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(Menu), @class = "btn btn-default" })
    </div>

}

@if (actionMethod == UIViewType.PostEdit.ToString())
{
    if (Model.Recipes == null)
    {
        Model.Recipes = new List<Recipe>();
    }

    if (Model.ID != 0)
    {
        using (Html.BeginForm("AddRecipe", "Menus", new { menuID = Model.ID }))
        {
            @Html.HiddenFor(x => x.ID);
            @Html.DropDownList("recipeID", RecipesList, "Choose a Recipe");
            <button type="submit" class="btn btn-default btn-sm  glyphicon glyphicon-plus" title="Add">Add Recipe</button>        }

        <dd>
            <table class="table">
                <tr>
                    <th>Recipe</th>
                    <th>Ingredients List</th>
                </tr>
                @foreach (var item in Model.Recipes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @foreach (Ingredient ingredient in item.Ingredients)
                            {
                                @ingredient.Name;   <br />
                            }
                        </td>
                        <td>
                            @Html.ActionLink(" ", "RemoveRecipe", new { menuID = Model.ID, recipeID = item.ID }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-trash", @title = "Delete" })
                        </td>
                    </tr>
                }
            </table>
        </dd>   }

    using (Html.BeginForm("AttachIngredient", "Menus", new { menuID = Model.ID }))
    {
        @Html.HiddenFor(x => x.ID);
        @Html.DropDownList("ingredientID", IngredientsList, "Choose a Ingredient");
        <button type="submit" class="btn btn-default btn-sm  glyphicon glyphicon-plus" title="Add">Add Ingredient</button>        }

    <dd>
        <table class="table">
            <tr>
                <th>Separate Ingredient</th>
            </tr>
            @foreach (var item in Model.Ingredients)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "RemoveIngredient", new { menuID = Model.ID, ingredientID = item.ID }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-trash", @title = "Delete" })
                    </td>
                </tr>
            }
        </table>
    </dd>   }
<div>
    @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(Menu), @class = "btn btn-default" })
    @if (Model.ID != 0)
    {
        @Html.ActionLink("Delete", UIViewType.Delete.ToString(), null, new { id = Model.ID }, new { @class = "btn btn-default" })
    }
</div>

 } 


@if (actionMethod == UIViewType.Delete.ToString())
{
    <h3>Are you sure you want to delete this menu: (@Model.Name) ?</h3>

    @Html.ActionLink("No - Back to List", UIViewType.Index.ToString(), null, new { @class = "btn btn-default" })
    using (Html.BeginForm(UIViewType.DeleteConfirmed.ToString(), UIControllerType.Menus.ToString(), new { id = Model.ID }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div>
                <input type="submit" value="Yes - Delete" class="btn btn-default" />
            </div>
        </div>
    }
}
@if (actionMethod == UIViewType.Details.ToString())
{
    <div>
        @Html.ActionLink("Back to List", UIViewType.Index.ToString(), null, new { T = typeof(Menu), @class = "btn btn-default" })
        @Html.ActionLink("Edit", UIViewType.Edit.ToString(), null, new { id = Model.ID, actionMethod = UIViewType.Edit.ToString() }, new { @class = "btn btn-default" })
        @Html.ActionLink("Delete", UIViewType.Delete.ToString(), null, new { id = Model.ID }, new { @class = "btn btn-default" })

    </div>
    <dt>
        @Html.DisplayNameFor(model => model.Recipes)
    </dt>

    <dd>
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Ingredients List</th>
            </tr>
            @foreach (var item in Model.Recipes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @foreach (Ingredient ingredient in item.Ingredients)
                        {
                            @ingredient.Name;   <br />
                        }
                    </td>
                </tr>
            }
            <tr>
                <th>Separate Ingredient</th> 
            </tr>
            @foreach (var ingredient in Model.Ingredients)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => ingredient.Name)
                </td>
            </tr>
            }
        </table>
    </dd>
}

LambAndLentil.UI/Views/Menus/Index.cshtml
 @model LambAndLentil.UI.Models.ListVM
@{
    ViewBag.Title = "Menu Index";
    string sourceActionMethod = "MenusIndex";
}

<h2>Menus</h2>

<p>
    @Html.ActionLink("Add Menu", LambAndLentil.UI.UIViewType.Create.ToString(), UIControllerType.Menus.ToString(), new { actionMethod = UIViewType.Create.ToString() }, null)

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Menus.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menus.First().MealType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menus.First().DayOfWeek)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Menus.First().Diners)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Menus) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MealType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DayOfWeek)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Diners)
        </td>
        <td>
            @Html.ActionLink(" ", UIViewType.Edit.ToString(), "Menus", new { id = item.ID, sourceActionMethod, actionMethod = UIViewType.Edit }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-edit", @title = "Edit" })
        </td>
        <td>
            @Html.ActionLink(" ", UIViewType.Details.ToString(), new { id = item.ID }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-list", @title = "Details" })
        </td>
        <td>
            @Html.ActionLink(" ", UIViewType.Details.ToString(), new
       {
           id = item.ID,
           actionMethod = UIViewType.Delete
       }, new { @class = "btn btn-default btn-sm  glyphicon glyphicon-trash", @title = "Delete" })
        </td>
    </tr>
}

</table>
</table>
<div class="pager">
    <h4>Lamb & Lentil</h4>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action(UIViewType.Index.ToString(), new { page = x }))
</div>